"use client";
import Head from "next/head";
import { Inter, Linden_Hill } from "next/font/google";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { toast } from "react-toastify";
import { API_URL } from "@/public/constant";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const route = useRouter();
  const [loginData, setLoginData] = useState({ email: '' });
 
  const handleInput = (e) => {
    const { name, value } = e.target;
    setLoginData({ ...loginData, [name]: value })
  };
  const handleSubmit = async (event) => {
   
    event.preventDefault();
    try {
      const response = await fetch(API_URL + "admin-forgot-password", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(loginData),
      });
      const data = await response.json();
      //set admin login details
      localStorage.setItem(
        "AdminLoginpassChange",
        JSON.stringify({
          login: true,
          token: data.accessToken,
        })
      );

      const Token = JSON.parse(localStorage.getItem("AdminLoginpassChange"));
      const token = Token.token;
      const header = {
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
      };

      if (data.status === true) {
        toast("Email send successfully");
      } else {
        toast("Login id or password wrong!");
      }
    } catch (error) {
      console.error("Error fetching data:", error);
    }
   
    // route.push("/reset/password");
  };

  // useEffect(() => {
  //   const keyDownHandler = (event) => {
  //     if (event.key === 'Enter') {
  //       event.preventDefault();
  //       handleSubmit();
  //     }
  //   }
  //   document.addEventListener('keydown', keyDownHandler);
  //   return () => {
  //     document.removeEventListener('keydown', keyDownHandler);
  //   }
  // }, [])

  const keyDownHandler = (event) => {
    if (event.key === 'Enter') {
      event.preventDefault();
      event.stopPropagation();
      handleSubmit(event);
    }
  }

  return (
    <>
      <Head>
        <title>Digital Sahkar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/header.png" type="image/png" sizes="32x32" />
      
      </Head>

      <main className="login-page digital-sahkar">
        <div className="loginmain">
          <input type="checkbox" id="chk" aria-hidden="true" />
          <div className="signup">
            <span class="logo login_fishfred_logo d-flex align-items-center"><span class="d-none d-lg-block p-3">Digital Sahkar</span></span>
            {/* <a
              className="logo login_fishfred_logo d-flex align-items-center"
              href="/admin/dashboard"
            >
          <img src="/logo.png" alt="profile" width="100" height="200" />
             <span className="d-none d-lg-block">FishFred</span>
              <span className="d-none d-lg-block">Digital Sahkar</span>
            </a> */}
          </div>
          <div className="login">
            <form>
              <div className="form-group forgotPage">
                <h2>Forgot Your Password ?</h2>
                <span>
                  Enter your email address and we'll send you the link to reset password.
                </span>
                <div className="row">
                  <div className="col-md-12">
                    <div className="input_form">
                      <input
                        className="form-control input_value_login"
                        type="email"
                        name="email"
                        value={loginData.email}
                        placeholder="Email"
                        required=""
                        onChange={handleInput}
                      />
                    </div>
                  </div>
                </div>
                <div className="resetPassBtn">
                  <button
                    type="submit"
                    onKeyDown={keyDownHandler}
                    onClick={(event) => handleSubmit(event)}

                  >
                    Reset Password
                  </button>
                </div>
                {/* <Link to="/reset/password"
                  type="submit"
                  onKeyDown={keyDownHandler}
                  onClick={(event) => handleSubmit(event)}
                  className="login_button"
                >
              Reset Password
                </Link> */}
                <div className="text-center">
                  <Link href="/" className="respassLink">Back to login page</Link>
                </div>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
