import "@/styles/globals.css";
import "@/styles/custom.css";
import "@/styles/sahkarnew.css";

import Script from "next/script";
import Head from "next/head";
import { useEffect } from "react";

import "@/styles/assets/vendor/bootstrap/css/bootstrap.min.css";
import "@/styles/assets/vendor/bootstrap-icons/bootstrap-icons.css";
import "@/styles/assets/vendor/boxicons/css/boxicons.min.css";
import "@/styles/assets/vendor/quill/quill.snow.css";
import "@/styles/assets/vendor/quill/quill.bubble.css";
import "@/styles/assets/vendor/remixicon/remixicon.css";
import "@/styles/assets/vendor/simple-datatables/style.css";
import "@/styles/assets/css/style.css";
import "@/styles/assets/css/responsive.css";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useRouter } from "next/router";
import { useSearchParams } from "next/navigation";

export default function App({ Component, pageProps }) {
  const router = useRouter();
  const respass_url = useSearchParams();
  const pass_token = respass_url.get('token');

  // const s_url ="https://coop.getanapp.co.in/";
  // const forgot_url = "https://coop.getanapp.co.in/reset";
  // const change_password_url = `https://coop.getanapp.co.in/reset/password?token=${pass_token}`;


  // const c_url = "http://localhost:3000/";
  // const forgot_url = "http://localhost:3000/reset";
  // const change_password_url = `http://localhost:3000/reset/password?token=${pass_token}`;


  // useEffect(() => {
  //   if (window.location.href === forgot_url) {
  //     router.push('/reset')
  //   }
  //   else if (window.location.href === change_password_url) {
  //     router.push('/reset/password')
  //   }
  //   else if (window.location.href !== c_url) {
  //     if (!localStorage.AdminLogin) {
  //       router.push("/");
  //     } else {
  //       console.log('working')
  //     }
  //   }

  //   if (window.location.href === c_url) {
  //     if (localStorage.AdminLogin) {
  //       // alert("Hello Anshu")
  //       localStorage.clear();
  //     }
  //   }
  // }, []);

  // useEffect(() => {
  //   if (!localStorage.AdminLogin) {
  //     router.push("/");
  //   }
  // }, []);

  return (
    <>
      <Head>
        <title>Sahkar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/header.png" type="image/png" sizes="32x32" />
       
      </Head>

      <Script src="/javas/apexcharts/apexcharts.min.js"></Script>
      <Script src="/javas/bootstrap/js/bootstrap.bundle.min.js"></Script>
      <Script src="/javas/chart.js/chart.umd.js"></Script>
      <Script src="/javas/echarts/echarts.min.js"></Script>
      <Script src="/javas/quill/quill.min.js"></Script>
      <Script src="/javas/simple-datatables/simple-datatables.js"></Script>
      <Script src="/javas/tinymce/tinymce.min.js"></Script>
      <Script src="/javas/php-email-form/validate.js"></Script>
      <Script src="/js/main.js" strategy="lazyOnload"></Script>

      <Component {...pageProps} />
      <ToastContainer
        position="top-right"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
      />
    </>
  );
}
